clean: 

	./cachet_vagrant.sh clean

base: 

	./cachet_vagrant.sh base

core:

	./cachet_vagrant.sh core

setup:

	./cachet_vagrant.sh setup

monitor:

	./cachet_vagrant.sh monitor

all:

	./cachet_vagrant.sh all

restore:

	./cachet_vagrant.sh restore